### ISSUE TITLE
vagrant up is failing

### ISSUE THREAD

**Issue by mortenwh** [metno/vagrant-s-enda#5]
I had to change the ubuntu box but then I got another error coming from `k3s.yml`: 
```
TASK [run k3s installation] ****************************************************
fatal: [k3s]: FAILED! => {
    "changed": false,
    "cmd": ["/root/install.sh"], 
    "delta": "0:00:14.212438",
    "end": "2022-03-08 14:31:41.127792", 
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2022-03-08 14:31:26.915354",
    "stderr": "Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.\nJob for k3s.service failed because the control process exited with error code.\nSee \"systemctl status k3s.service\" and \"journalctl -xeu k3s.service\" for details.",
    "stderr_lines": [
            "Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.",
            "Job for k3s.service failed because the control process exited with error code.", 
            "See \"systemctl status k3s.service\" and \"journalctl -xeu k3s.service\" for details."
        ],
    "stdout": "
        [INFO]  Using v1.20.6+k3s1 as release\n
        [INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.6+k3s1/sha256sum-amd64.txt\n
        [INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.20.6+k3s1/k3s\n
        [INFO]  Verifying binary download\n
        [INFO]  Installing k3s to /usr/local/bin/k3s\n
        [INFO]  Creating /usr/local/bin/kubectl symlink to k3s\n
        [INFO]  Creating /usr/local/bin/crictl symlink to k3s\n
        [INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr\n
        [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh\n
        [INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh\n
        [INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env\n
        [INFO]  systemd: Creating service file /etc/systemd/system/k3s.service\n
        [INFO]  systemd: Enabling k3s unit\n
        [INFO]  systemd: Starting k3s",
    "stdout_lines": [
        "[INFO]  Using v1.20.6+k3s1 as release",
        "[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.20.6+k3s1/sha256sum-amd64.txt",
        "[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.20.6+k3s1/k3s",
        "[INFO]  Verifying binary download",
        "[INFO]  Installing k3s to /usr/local/bin/k3s",
        "[INFO]  Creating /usr/local/bin/kubectl symlink to k3s",
        "[INFO]  Creating /usr/local/bin/crictl symlink to k3s",
        "[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr",
        "[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh",
        "[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh",
        "[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env",
        "[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service",
        "[INFO]  systemd: Enabling k3s unit",
        "[INFO]  systemd: Starting k3s"
    ]
}
```

Maybe wrong k3s version? 

@aheimsbakk - can you have a look? I don't understand this..

Output of recommended commands:

```
vagrant@k3s:~$ systemctl status k3s.service
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-03-08 21:07:34 UTC; 3s ago
       Docs: https://k3s.io
    Process: 530785 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 530786 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 530787 ExecStart=/usr/local/bin/k3s server --docker --node-ip 10.10.10.10 --disable traefik --default-local-s>
   Main PID: 530787 (code=exited, status=255/EXCEPTION)
        CPU: 1.282s
```

```
vagrant@k3s:~$ sudo journalctl -xeu k3s.service
Mar 08 21:09:57 k3s k3s[533877]: goroutine 2518 [select]:
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.(*timeBudgetImpl).perio>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/time_bu>
Mar 08 21:09:57 k3s k3s[533877]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.newTimeBudget
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/time_bu>
Mar 08 21:09:57 k3s k3s[533877]: goroutine 2519 [select]:
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).dispatchEvent>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFro>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: goroutine 2520 [select]:
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc0>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/cache/reflector.go:4>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/cache/reflector.go:4>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).startCaching(>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFromConfig.fun>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc004>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc004371f88>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc004343f88,>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFromConfig.fun>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFro>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.>
Mar 08 21:09:57 k3s k3s[533877]: goroutine 2521 [select]:
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0031ffb00>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1>
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0031ffb00,>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:1>
Mar 08 21:09:57 k3s k3s[533877]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/regis>
Mar 08 21:09:57 k3s k3s[533877]: goroutine 2509 [select]:
Mar 08 21:09:57 k3s k3s[533877]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).run(0xc001a>
Mar 08 21:09:57 k3s k3s[533877]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.>
lines 961-1001/1001 (END)
```

**Comment by mortenwh** [comment]
@aheimsbakk - kan du se på denne? Skjønner du hva som foregår?

**Comment by aheimsbakk** [comment]
Jeg må ta en titt på denne...
